In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn import metrics as sm

In [ ]:
df=pd.read_csv(r"/content/airline_passenger_satisfaction.csv")

In [ ]:
df.head(5)

,ID,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,...,On-board Service,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction
0,1,Male,48,First-time,Business,Business,821,2,5.0,3,...,3,5,2,5,5,5,3,5,5,Neutral or Dissatisfied
1,2,Female,35,Returning,Business,Business,821,26,39.0,2,...,5,4,5,5,3,5,2,5,5,Satisfied
2,3,Male,41,Returning,Business,Business,853,0,0.0,4,...,3,5,3,5,5,3,4,3,3,Satisfied
3,4,Male,50,Returning,Business,Business,1905,0,0.0,2,...,5,5,5,4,4,5,2,5,5,Satisfied
4,5,Female,49,Returning,Business,Business,3470,0,1.0,3,...,3,4,4,5,4,3,3,3,3,Satisfied

In [ ]:
df.columns

Index(['ID', 'Gender', 'Age', 'Customer Type', 'Type of Travel', 'Class',
       'Flight Distance', 'Departure Delay', 'Arrival Delay',
       'Departure and Arrival Time Convenience', 'Ease of Online Booking',
       'Check-in Service', 'Online Boarding', 'Gate Location',
       'On-board Service', 'Seat Comfort', 'Leg Room Service', 'Cleanliness',
       'Food and Drink', 'In-flight Service', 'In-flight Wifi Service',
       'In-flight Entertainment', 'Baggage Handling', 'Satisfaction'],
      dtype='object')

In [ ]:
df.shape

(129880, 24)

In [ ]:
df.drop(["ID"], axis = 1, inplace = True, errors = "ignore")

In [ ]:
df.isna().sum()* 100 / len(df)

Gender                                    0.000000
Age                                       0.000000
Customer Type                             0.000000
Type of Travel                            0.000000
Class                                     0.000000
Flight Distance                           0.000000
Departure Delay                           0.000000
Arrival Delay                             0.302587
Departure and Arrival Time Convenience    0.000000
Ease of Online Booking                    0.000000
Check-in Service                          0.000000
Online Boarding                           0.000000
Gate Location                             0.000000
On-board Service                          0.000000
Seat Comfort                              0.000000
Leg Room Service                          0.000000
Cleanliness                               0.000000
Food and Drink                            0.000000
In-flight Service                         0.000000
In-flight Wifi Service                    0.000000
In-flight Entertainment                   0.000000
Baggage Handling                          0.000000
Satisfaction                              0.000000
dtype: float64

In [ ]:
df.dropna(inplace = True)

In [ ]:

d = {"Business" : 3, "Eco Plus" : 2, "Eco" : 1}
df['Class'] = df['Class'].map(d)
df['Class'].unique()

array([ 3., nan])

In [ ]:
d = {"Neutral or Dissatisfied" : 0, "Satisfied" : 1}
df['Satisfaction'] = df['Satisfaction'].map(d)
df['Satisfaction'].unique()

array([0, 1])

In [ ]:
df.head()

,Gender,Age,Customer Type,Type of Travel,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,Ease of Online Booking,...,On-board Service,Seat Comfort,Leg Room Service,Cleanliness,Food and Drink,In-flight Service,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction
0,Male,48,First-time,Business,3.0,821,2,5.0,3,3,...,3,5,2,5,5,5,3,5,5,0
1,Female,35,Returning,Business,3.0,821,26,39.0,2,2,...,5,4,5,5,3,5,2,5,5,1
2,Male,41,Returning,Business,3.0,853,0,0.0,4,4,...,3,5,3,5,5,3,4,3,3,1
3,Male,50,Returning,Business,3.0,1905,0,0.0,2,2,...,5,5,5,4,4,5,2,5,5,1
4,Female,49,Returning,Business,3.0,3470,0,1.0,3,3,...,3,4,4,5,4,3,3,3,3,1

In [ ]:
df.select_dtypes(include = "number").columns

Index(['Age', 'Class', 'Flight Distance', 'Departure Delay', 'Arrival Delay',
       'Departure and Arrival Time Convenience', 'Ease of Online Booking',
       'Check-in Service', 'Online Boarding', 'Gate Location',
       'On-board Service', 'Seat Comfort', 'Leg Room Service', 'Cleanliness',
       'Food and Drink', 'In-flight Service', 'In-flight Wifi Service',
       'In-flight Entertainment', 'Baggage Handling', 'Satisfaction'],
      dtype='object')

In [ ]:
df = pd.get_dummies(df, columns = ['Gender', 'Customer Type', 'Type of Travel'])
df.head(2)

,Age,Class,Flight Distance,Departure Delay,Arrival Delay,Departure and Arrival Time Convenience,Ease of Online Booking,Check-in Service,Online Boarding,Gate Location,...,In-flight Wifi Service,In-flight Entertainment,Baggage Handling,Satisfaction,Gender_Female,Gender_Male,Customer Type_First-time,Customer Type_Returning,Type of Travel_Business,Type of Travel_Personal
0,48,3.0,821,2,5.0,3,3,4,3,3,...,3,5,5,0,False,True,True,False,True,False
1,35,3.0,821,26,39.0,2,2,3,5,2,...,2,5,5,1,True,False,False,True,True,False

In [ ]:
Y = df['Satisfaction']
X = df.loc[:, df.columns != "Satisfaction"]

In [ ]:
X_train, X_test, y_train, y_test  = train_test_split(X, Y, test_size = 0.2, random_state = 77)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((103589, 25), (25898, 25), (103589,), (25898,))

Decision Tree to predict Customer Satisfacation

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
DT = DecisionTreeClassifier(class_weight = "balanced")
DT.fit(X_train, y_train)

DecisionTreeClassifier(class_weight='balanced')

In [ ]:
test_predictions = DT.predict(X_test)
train_predictions = DT.predict(X_train)

In [ ]:
test_predictions

array([1, 1, 1, ..., 0, 1, 1])

In [ ]:
print(confusion_matrix(y_test, test_predictions))
print(classification_report(y_test, test_predictions))

print(confusion_matrix(y_train, train_predictions))
print(classification_report(y_train, train_predictions))

[[13959   763]
 [  714 10462]]
              precision    recall  f1-score   support

           0       0.95      0.95      0.95     14722
           1       0.93      0.94      0.93     11176

    accuracy                           0.94     25898
   macro avg       0.94      0.94      0.94     25898
weighted avg       0.94      0.94      0.94     25898

[[58503     0]
 [    0 45086]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     58503
           1       1.00      1.00      1.00     45086

    accuracy                           1.00    103589
   macro avg       1.00      1.00      1.00    103589
weighted avg       1.00      1.00      1.00    103589

Random Forest Classifier

In [ ]:
RF = RandomForestClassifier(n_estimators = 99, class_weight= "balanced")
RF.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=99)

In [ ]:
test_predictions = RF.predict(X_test)
train_predictions = RF.predict(X_train)

In [ ]:
print(confusion_matrix(y_test, test_predictions))
print(classification_report(y_test, test_predictions))

print(confusion_matrix(y_train, train_predictions))
print(classification_report(y_train, train_predictions))

[[14422   300]
 [  678 10498]]
              precision    recall  f1-score   support

           0       0.96      0.98      0.97     14722
           1       0.97      0.94      0.96     11176

    accuracy                           0.96     25898
   macro avg       0.96      0.96      0.96     25898
weighted avg       0.96      0.96      0.96     25898

[[58503     0]
 [    1 45085]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     58503
           1       1.00      1.00      1.00     45086

    accuracy                           1.00    103589
   macro avg       1.00      1.00      1.00    103589
weighted avg       1.00      1.00      1.00    103589